### ISSUE TITLE
Disallow and allow new elements

### ISSUE THREAD

**Issue by dstollie** [cstigler/node-xhtml-purifier#2]
I cant find a way to add or disallow default elements.. can you tell me how?

**Comment by cstigler** [comment]
@dstollie Unfortunately there's no simple on/off switch right now. If an element is handled in XHTMLPurifier.js, it will be output, anything that's not handled won't be. So you have to add rules to process it there.

Check out [this commit](https://github.com/zaption/node-xhtml-purifier/commit/6abdaf82ac9b80c4bffa44e95afd4247af8aba98) for an example of how to add (he's adding `<var>` and `<sup>` elements)

**Comment by dstollie** [comment]
Thanks! Someone build the functionality to skip and add new tags and attributes programatically based on your work. Might be worth for you or others to look at that: https://github.com/cristo-rabani/meteor-universe-html-purifier
